// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.

import type { Sync } from "@engine";

import * as sync_sample from "./sample.sync.ts";
import * as sync_user_auth from "./user_auth.sync.ts";
import * as sync_library from "./library.sync.ts";
import * as sync_annotate from "./annotate.sync.ts";
import * as sync_checkpoint_quiz from "./checkpoint_quiz.sync.ts";
import * as sync_focus_timer from "./focus_timer.sync.ts";
import * as sync_reading_progress from "./reading_progress.sync.ts";

const allSyncs: Record<string, Sync> = {};

for (const [name, func] of Object.entries(sync_sample)) {
  if (typeof func === "function") {
    allSyncs[`sample.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_user_auth)) {
  if (typeof func === "function") {
    allSyncs[`user_auth.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_library)) {
  if (typeof func === "function") {
    allSyncs[`library.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_annotate)) {
  if (typeof func === "function") {
    allSyncs[`annotate.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_checkpoint_quiz)) {
  if (typeof func === "function") {
    allSyncs[`checkpoint_quiz.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_focus_timer)) {
  if (typeof func === "function") {
    allSyncs[`focus_timer.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_reading_progress)) {
  if (typeof func === "function") {
    allSyncs[`reading_progress.${name}`] = func as Sync;
  }
}

export default allSyncs;
